name: Deploy to AWS EC2

on:
  push:
    branches:
      - main # Change this to 'master' if your main branch is called master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu # Default username for Ubuntu AMIs
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to the project directory
            cd ~/inventory
            
            # Pull the latest code from GitHub
            git pull origin main
            
            # Rebuild and restart the docker containers in the background
            docker-compose up --build -d
